run:
	@echo "Activating virtual environment..."
	. venv/Scripts/activate
	@echo "Running app.py..."
	python app.py

test:
	@echo "Activating virtual environment..."
	. venv/Scripts/activate
	@echo "Running tests..."
	python test_routes.py